export declare enum ConversationType {
    CHAT_REQUEST = "CHAT_REQUEST",
    OFFLINE_CHAT_REQUEST = "OFFLINE_CHAT_REQUEST",
    VIDEO_REQUEST = "VIDEO_REQUEST",
    AUDIO_REQUEST = "AUDIO_REQUEST",
    HEADLESS_BROWSER_REQUEST = "HEADLESS_BROWSER_REQUEST",
    DOMCAP_BROWSER_REQUEST = "DOMCAP_BROWSER_REQUEST",
    MOBILE_COBROWSING_REQUEST = "MOBILE_COBROWSING_REQUEST"
}
